name: CI
env:
  GLOBAL_ENV1: value1
  GLOBAL_ENV2: value2
steps:
  - name: Install Python and pip
    command: |
      if ! command -v python3 &> /dev/null; then
        apt-get update && apt-get install -y python3 python3-venv
      fi
  - name: Set up virtual environment
    command: python3 -m venv venv
  - name: Install dependencies
    command: venv/bin/pip install -r requirements.txt
  - name: Run tests
    command: venv/bin/python -m unittest discover -s tests
  - name: Inspect Env Vars
    env:
      STEP_ENV: value3
    command: echo $GLOBAL_ENV1 $GLOBAL_ENV2 $STEP_ENV
